-- Phase 3: VAT / GTGT store + product rates
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "vatEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "defaultVatRateBps" INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "vatRateBps" INTEGER;
