ALTER TABLE "SaleReturnLine" ADD COLUMN IF NOT EXISTS "vatRateBps" INTEGER;
ALTER TABLE "SaleReturnLine" ADD COLUMN IF NOT EXISTS "netVnd" INTEGER;
ALTER TABLE "SaleReturnLine" ADD COLUMN IF NOT EXISTS "vatVnd" INTEGER;
